services:
  app:
    build:
      dockerfile: ./docker-build/app/Dockerfile_bot
      context: ./
    network_mode: host
    environment:
      APP_CONFIG__DB__ECHO: 0
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:16.9
    network_mode: host
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  celery-1:
    build:
      context: ./
      dockerfile: ./docker-build/app/Dockerfile
    network_mode: host
    command: celery -A apps.celery.celery_app worker --pool=threads --loglevel=info -c 1
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: ./docker-build/app/Dockerfile_base
    network_mode: host
    command: celery -A apps.celery.celery_app flower --port=5555 \
      --basic_auth=${APP_CONFIG__FLOWER__USER}:${APP_CONFIG__FLOWER__PASSWORD}
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped

  redis:
    image: redis:8
    container_name: redis
    network_mode: host
    command: ["redis-server", "--requirepass", "${APP_CONFIG__REDIS__PASSWORD}"]
    restart: unless-stopped

volumes:
  pgdata:
