services:
  app:
    build:
      dockerfile: ./docker-build/app/Dockerfile_bot
      context: ./
    ports:
      - "8004:8000"
    container_name: ozon_bot
    environment:
      APP_CONFIG__DB__ECHO: 0
    env_file:
      - ./src/.env

  celery:
    build:
      context: ./
      dockerfile: ./docker-build/app/Dockerfile_vnc
    container_name: ozon_celery
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/src
    restart: unless-stopped

  celery_tg:
    build:
      context: ./
      dockerfile: ./docker-build/app/Dockerfile_base
    container_name: ozon_celery_tg
    command: celery -A apps.celery.celery_app worker -Q telegram --pool=threads --loglevel=info -c 1 --hostname=telegram@%h
    env_file:
      - ./src/.env
    environment:
      - PYTHONPATH=/src
    restart: unless-stopped

  flower:
    build:
      context: .
      dockerfile: ./docker-build/app/Dockerfile_base
    ports:
      - "5556:5556"
    container_name: ozon_flower
    command: celery -A apps.celery.celery_app flower --port=5556 \
      --basic_auth=${APP_CONFIG__FLOWER__USER}:${APP_CONFIG__FLOWER__PASSWORD}
    env_file:
      - ./src/.env
    environment:
      PYTHONPATH: /app/src
    restart: unless-stopped

networks:
  default:
    external:
      name: shared_network