FROM python:3.13-slim-bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:99
ENV VNC_PASSWORD=123456
ENV CHROME_BIN=/usr/bin/chromium

WORKDIR /src

# Устанавливаем системные зависимости, VNC, LXDE, Chromium
RUN apt-get update && apt-get install -y \
    x11vnc \
    fluxbox \
    lxde-core \
    lxterminal \
    chromium \
    wget curl xauth ca-certificates fonts-liberation \
    libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 libcups2 \
    libdbus-1-3 libdrm2 libgbm1 libglib2.0-0 libgtk-3-0 \
    libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 \
    libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 \
    libxshmfence1 libxss1 libxtst6 libgl1-mesa-glx libgbm-dev \
    xvfb --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Устанавливаем Poetry
RUN pip install --upgrade pip wheel setuptools poetry==1.6.1

# Копируем poetry-файлы и устанавливаем зависимости
COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && poetry install --no-root

# Копируем проект и стартовый скрипт
COPY src/ .

RUN chmod +x runcelery.sh

EXPOSE 5900

CMD ["./runcelery.sh"]
