FROM python:3.13.3-slim-bookworm

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DISPLAY=:99 \
    CHROME_BIN=/usr/bin/chromium

WORKDIR /app

# Устанавливаем системные зависимости для Chromium и Xvfb
RUN apt-get update && apt-get install -y \
    chromium=137.* \
    chromium-driver \
    xauth \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libx11-6 \
    libxcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libxshmfence1 \
    libxss1 \
    libxtst6 \
    libgl1-mesa-glx \
    libgbm-dev \
    x11-utils \
    x11-xserver-utils \
    xvfb \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Устанавливаем Python-зависимости
RUN pip install --upgrade pip wheel "poetry==2.1" setuptools

RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

COPY /src .

# Скрипт уже внутри, но нужно сделать исполняемым
RUN chmod +x run_celery.sh

ENTRYPOINT ["./run_celery.sh"]
CMD ["./run_celery.sh"]

# Запуск Celery worker через Xvfb
#CMD xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" \
#    celery -A apps.celery.celery_app worker \
#    --pool=threads \
#    --loglevel=info \
#    -c 1
