FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1
ENV VNC_PASSWORD=123456
ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /src

# Устанавливаем системные зависимости, X11, VNC, LXDE, Chromium и Python
RUN apt-get update && apt-get install -y --no-install-recommends \
    x11vnc \
    fluxbox \
    lxde-core \
    lxterminal \
    chromium-browser \
    python3 python3-pip python3-setuptools python3-venv \
    wget curl \
    xauth \
    ca-certificates \
    fonts-liberation \
    libasound2 libatk-bridge2.0-0 libatk1.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 libxss1 libxtst6 libgl1-mesa-glx libgbm-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем Poetry
RUN pip3 install --upgrade pip wheel setuptools poetry==2.1

# Копируем poetry-файлы и устанавливаем зависимости
COPY pyproject.toml poetry.lock /app/
RUN poetry config virtualenvs.create false && poetry install --no-root

# Копируем проект
COPY ./src .

RUN chmod +x runcelery.sh

CMD ["./runcelery.sh"]
