"""init

Revision ID: 257a825df0cb
Revises:
Create Date: 2025-05-21 02:42:42.087378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "257a825df0cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("ozon_price", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("old_price", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["url"], ["links.url"], name=op.f("fk_links_url_links")
        ),
        sa.PrimaryKeyConstraint("url", name=op.f("pk_links")),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("last_command", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id", name=op.f("pk_users")),
    )
    op.create_table(
        "subscribes",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["users.telegram_id"],
            name=op.f("fk_subscribes_telegram_id_users"),
        ),
        sa.PrimaryKeyConstraint("url", name=op.f("pk_subscribes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscribes")
    op.drop_table("users")
    op.drop_table("links")
    # ### end Alembic commands ###
